# Generated by Django 4.2 on 2023-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonology',
            new_name='technology',
        ),
    ]
