# Generated by Django 4.2 on 2023-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gh_url',
            field=models.URLField(null=True),
        ),
    ]
