# Generated by Django 4.2.1 on 2023-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameassets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='gif',
        ),
    ]
